blk-throttle: Fix W=1 build issue in tg_prfill_limit()
For when using gcc 8 and above, the following warning can be seen when
compiling blk-throttle.c:

block/blk-throttle.c: In function ‘tg_prfill_limit’:
block/blk-throttle.c:1539:53: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
    snprintf(idle_time, sizeof(idle_time), " idle=%lu",
                                                     ^
block/blk-throttle.c:1539:4: note: ‘snprintf’ output between 8 and 27 bytes into a destination of size 26
    snprintf(idle_time, sizeof(idle_time), " idle=%lu",
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     tg->idletime_threshold_conf);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
block/blk-throttle.c:1546:15: error: ‘%lu’ directive output may be truncated writing between 1 and 20 bytes into a region of size 17 [-Werror=format-truncation=]
     " latency=%lu", tg->latency_target_conf);
               ^~~
block/blk-throttle.c:1546:5: note: directive argument in the range [0, 18446744073709551614]
     " latency=%lu", tg->latency_target_conf);
     ^~~~~~~~~~~~~~
block/blk-throttle.c:1545:4: note: ‘snprintf’ output between 11 and 30 bytes into a destination of size 26
    snprintf(latency_time, sizeof(latency_time),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     " latency=%lu", tg->latency_target_conf);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: block/blk-throttle.o] Error 1

Increase idle_time[] and latency_time[] sizes to clear the warning.

Fixes: ec80991d6fc2c ("blk-throttle: add interface for per-cgroup target latency")
Signed-off-by: John Garry <john.g.garry@oracle.com>